<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="13" total="16" passed="1">
  <reporter-output>
    <line>
      <![CDATA[<a href='C:\Users\eduarte-as\eclipse-workspace\HiyaAutomationFramework\target\surefire-reports\failure_screenshots\ValidCallTest_07_12_2017_03_36_30.png'> <img src='C:\Users\eduarte-as\eclipse-workspace\HiyaAutomationFramework\target\surefire-reports\failure_screenshots\ValidCallTest_07_12_2017_03_36_30.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\eduarte-as\eclipse-workspace\HiyaAutomationFramework\target\surefire-reports\failure_screenshots\ValidCallTest_07_12_2017_03_37_52.png'> <img src='C:\Users\eduarte-as\eclipse-workspace\HiyaAutomationFramework\target\surefire-reports\failure_screenshots\ValidCallTest_07_12_2017_03_37_52.png' height='100' width='100'/> </a>]]>
    </line>
  </reporter-output>
  <suite name="TestSuite" duration-ms="122548" started-at="2017-12-07T21:35:51Z" finished-at="2017-12-07T21:37:54Z">
    <groups>
    </groups>
    <test name="Appium" duration-ms="122548" started-at="2017-12-07T21:35:51Z" finished-at="2017-12-07T21:37:54Z">
      <class name="Tests.HiyaTests">
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Tests.HiyaTests@bfbc86]" name="setup" is-config="true" duration-ms="12206" started-at="2017-12-07T15:35:51Z" finished-at="2017-12-07T15:36:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android Emulator]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[6.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[/apk/Hiya.apk]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[http://127.0.0.1:4723/wd/hub]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="ValidCallTest(java.lang.String)[pri:0, instance:Tests.HiyaTests@bfbc86]" name="ValidCallTest" duration-ms="26851" started-at="2017-12-07T15:36:03Z" data-provider="phoneNumbers" finished-at="2017-12-07T15:36:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[206-555-0181]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at Tests.HiyaTests.ValidCallTest(HiyaTests.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:459)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\eduarte-as\eclipse-workspace\HiyaAutomationFramework\target\surefire-reports\failure_screenshots\ValidCallTest_07_12_2017_03_36_30.png'> <img src='C:\Users\eduarte-as\eclipse-workspace\HiyaAutomationFramework\target\surefire-reports\failure_screenshots\ValidCallTest_07_12_2017_03_36_30.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- ValidCallTest -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:Tests.HiyaTests@bfbc86]" name="cleanUp" is-config="true" duration-ms="586" started-at="2017-12-07T15:36:31Z" finished-at="2017-12-07T15:36:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Tests.HiyaTests@bfbc86]" name="setup" is-config="true" duration-ms="13694" started-at="2017-12-07T15:36:32Z" finished-at="2017-12-07T15:36:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android Emulator]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[6.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[/apk/Hiya.apk]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[http://127.0.0.1:4723/wd/hub]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="ValidCallTest(java.lang.String)[pri:0, instance:Tests.HiyaTests@bfbc86]" name="ValidCallTest" duration-ms="26025" started-at="2017-12-07T15:36:45Z" data-provider="phoneNumbers" finished-at="2017-12-07T15:37:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[206-555-0180]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidCallTest -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:Tests.HiyaTests@bfbc86]" name="cleanUp" is-config="true" duration-ms="505" started-at="2017-12-07T15:37:12Z" finished-at="2017-12-07T15:37:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Tests.HiyaTests@bfbc86]" name="setup" is-config="true" duration-ms="13572" started-at="2017-12-07T15:37:12Z" finished-at="2017-12-07T15:37:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Android Emulator]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[6.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Android]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[/apk/Hiya.apk]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[http://127.0.0.1:4723/wd/hub]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="ValidCallTest(java.lang.String)[pri:0, instance:Tests.HiyaTests@bfbc86]" name="ValidCallTest" duration-ms="26326" started-at="2017-12-07T15:37:26Z" data-provider="phoneNumbers" finished-at="2017-12-07T15:37:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[206-555-0186]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at Tests.HiyaTests.ValidCallTest(HiyaTests.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:459)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\eduarte-as\eclipse-workspace\HiyaAutomationFramework\target\surefire-reports\failure_screenshots\ValidCallTest_07_12_2017_03_37_52.png'> <img src='C:\Users\eduarte-as\eclipse-workspace\HiyaAutomationFramework\target\surefire-reports\failure_screenshots\ValidCallTest_07_12_2017_03_37_52.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- ValidCallTest -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:Tests.HiyaTests@bfbc86]" name="cleanUp" is-config="true" duration-ms="570" started-at="2017-12-07T15:37:53Z" finished-at="2017-12-07T15:37:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- Tests.HiyaTests -->
    </test> <!-- Appium -->
  </suite> <!-- TestSuite -->
</testng-results>
